sudo: required
services:
  - docker

# build and run tests
before_install:
  # name the build with any name
  - docker build -t zwilderrr/react-test -f ./client/Docker.dev
  # note - other builds could go here to be executed in `script`

script:
  - docker run -e CI=true zwilderrr/react-test npm test

# after a non-zero exit code, build all the images
after_success:
  - docker build -t zwilderrr/multi-client ./client
  - docker build -t zwilderrr/multi-nginx ./nginx
  - docker build -t zwilderrr/multi-server ./server
  - docker build -t zwilderrr/multi-worker ./worker
  # log in to docker cli with env variables set on traviss
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push zwilderrr/multi-client
  - docker push zwilderrr/multi-nginx
  - docker push zwilderrr/multi-server
  - docker push zwilderrr/multi-worker
